### ISSUE TITLE
INFO: How I can instal on my cPanel VPS?

### ISSUE THREAD

**Issue by testt23** [zecure/shadowd_php#15]
Hi everyone, I think this is a great solution to minimize the risks to the web environment.  However, how can I install the system on my VPS?  I use CentOS and I bought a cPanel for it.  Also, can I only use the PHP version?

**Comment by zit-hb** [comment]
Hey. You can install it on a CentOS VPS but it is not possible to do this with cPanel. You will have to connect to your server with SSH and follow this instructions: https://shadowd.zecure.org/overview/shadowd/

**Comment by testt23** [comment]
Ok. Thanks you very much.

**Comment by zit-hb** [comment]
You are welcome.
