### ISSUE TITLE
Is shadow daemon still being maintained?

### ISSUE THREAD

**Issue by rockoo** [zecure/shadowd_php#19]
The last update to the project was 4 years ago and there is no maintenance status anywhere

**Comment by zit-hb** [comment]
It is still maintained but not actively developed anymore. What that means is that I will still release security updates and the like but no new functionality. The project does what it is supposed to do, so there is no reason.

At least there will be no major features, I still want to add custom error pages and some similar improvements, it just does not have a very high priority.

**Comment by rockoo** [comment]
> It is still maintained but not actively developed anymore. What that means is that I will still release security updates and the like but no new functionality. The project does what it is supposed to do, so there is no reason.
> 
> At least there will be no major features, I still want to add custom error pages and some similar improvements, it just does not have a very high priority.

Thank you for the explanation. Appreciate it.
