### ISSUE TITLE
PHP error: Invalid argument 

### ISSUE THREAD

**Issue by ghost** [zecure/shadowd_php#2]
Error:
 "PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wordpress/shadowd_php/src/shadowd_connector.php on line 233, referer: http://_site_/wordpress/"

I really don't know what I am doing wrong. I am pretty sure it has to be an error with me, however I can't find where.

EDIT: I think everything is working now, the error stopped showing up so I probably had something set wrong. Though I cant be sure because I really have a ton of questions/things I am trying to figure out. I will post again if I figure out what I had wrong.

**Comment by zit-hb** [comment]
Hey there,

before you start investing too much time, let me say that I will release version 2.0 in about a week. I have been working many months on it and it will make a lot of things easier and better. It will also fix some non-critical bugs that I have found in the last weeks. Rules from version 1 will be importable, but I would still recommend to wait the week if you want to deploy it on a production system. I am also rewriting parts of the documentation to make things more clear. If you have questions though don't hesitate to ask. If I know what is unclear to people I will spend extra efforts on that parts.

Now about the error. Even though it is fixed, it was probably related to an invalid _ignore_ file. I will add another check there in version 2 to show a more meaningful error message in such a case.

Best regards,
Hendrik

**Comment by ghost** [comment]
Ahh! I am soo glad to hear about version two! I read about your project awhile ago and wanted to start learning it. I have finally gotten around to doing so and I must say nicely done. 
        As for the error, you hit the nail on the head. I checked the timestamps and compared it to the changes I had made and found I was trying to set my ignore file.  Thanks again for the help. It does mean a lot for someone who is new/learning this sort of thing.
Warm Regards,
Austin
On Jan 3, 2016 4:37 AM, Hendrik Buchwald notifications@github.com wrote:Hey there,

before you start investing too much time, let me say that I will release version 2.0 in about a week. I have been working many months on it and it will make a lot of things easier and better. It will also fix some non-critical bugs that I have found in the last weeks. Rules from version 1 will be importable, but I would still recommend to wait the week if you want to deploy it on a production system.

Now about the error. Even though it is fixed, it was probably related to an invalid ignore file. I will add another check there in version 2 to show a more meaningful error message in such a case.

Best regards,
Hendrik

**Comment by zit-hb** [comment]
Thanks and you are welcome.
