### ISSUE TITLE
Problem with PHP connector 

### ISSUE THREAD

**Issue by Lorenzo1212-cell** [zecure/shadowd_php#20]
Good Afternoon , I've try to install PHP connector on shadow daemon . But the installation guide isn't clear , how to do it . So to install PHP connector I have to execute this command "**git clone https://github.com/zecure/shadowd_php.git**" and should be done , right ? 

the part that i don't have understand is " To install the connector you have to move the directory src to a location that is accessible by the web server, e.g., /usr/share/shadowd/php.

Global
If you want to enable Shadow Daemon globally you can set auto_prepend_file to /usr/share/shadowd/php/Connector.php in your php.ini file (for example, /etc/php/7.2/cgi/php.ini). The change will take effect after you restart your web server, but you should wait with that until the configuration of the module is completely done. " so what I have to do

**Comment by zit-hb** [comment]
Hey. The `git clone` downloads it. You can move the directory with `mv`: `mkdir /usr/share/shadowd && mv shadowd_php/src /usr/share/shadowd/php`. After that you have to specify the value exactly like in the text that you quoted (of course the paths may change depending on PHP version). Don't forget to create the configuration file at the end, it will not work without a valid configuration file. You will just see 500 errors then.

**Comment by Lorenzo1212-cell** [comment]
Thank you for your quick reply . So I've execute mkdir /usr/share/shadowd && mv shadowd_php /usr/share/shadowd/php , and changed the directory . what i have to do ? I think that I have to install PHP , right ? 

Don't forget to create the configuration file at the end, it will not work without a valid configuration file, to do this  there is a manual ?

**Comment by zit-hb** [comment]
You are welcome! My question here would be: if you don't have PHP installed already, what are you trying to protect? Meaning: the usual use case is that you are running a web application already, for example a WordPress blog. Then you install the connector on the server where the application is running, and thus connect the application and shadowd. The WordPress blog would then be protected by shadowd (if enabled).

**Comment by Lorenzo1212-cell** [comment]
okay okay  , perfectly understand now . I know where my mistake is . So I must to install Shadow Daemon on the same server , where my application, blog , etc  running right ?

**Comment by zit-hb** [comment]
So Shadow Daemon consists of 3 components: shadowd, the UI, and the connector. It does not matter where shadowd and the UI are running, but the connector has to be installed on the server that you want to protect.

You can find more details here: https://shadowd.zecure.org/documentation/architecture/
