### ISSUE TITLE
Testing shadowd daemon with DVWA on ubuntu 18.04

### ISSUE THREAD

**Issue by chakir123123** [zecure/shadowd_php#28]
Hi,
I have installed shadow daemon as recommanded to do inhttps://shadowd.zecure.org/overview/shadowd/ but it doesn’t work.
To configure connector php i used the follwoing commands :
        1-git clone  https://github.com/zecure/shadowd_php.git
        2- mkdir  /usr/share/shadowd
        3- mv shadowd_php/src /usr/share/shadowd/php
        4- I added this ligne  php_value  auto_prepend_file  "/usr/share/shadowd/php/Connector.php" to my  php.ini
        5- mkdir /etc/shadowd
        6- Cp /misc/examples/connectors .ini  /etc/shadowd/connectors.ini and then I edit it .
I restarted apache2 and enabled blacklist rules and everything works fine but when I launch SQLI attacks from DVWA to test shadowd, it doesn't work!
N.B:I installed the dvwa on the same host as shadowd
![git](https://user-images.githubusercontent.com/62439237/93899304-78f89c00-fcf4-11ea-82f5-7ae3e18d7cc9.PNG)

**Comment by zit-hb** [comment]
Hey, at the moment in your configuration only the blacklist is enabled, so Shadow Daemon only checks for known attack patterns. `1' and 1=1#` is too simple to trigger [any of the blacklist filters](https://demo.shadowd.zecure.org/parameter/459911). Try to reduce the "blacklist threshold" to a lower value like `3`, and then test a payload like `1' UNION SELECT password FROM users-- -`. This will generate an [impact of 7](https://demo.shadowd.zecure.org/parameter/459920).

If you want to detect ID as an attack if it is not numeric you have to create rules for the whitelist first and then enable the whitelist: https://shadowd.zecure.org/tutorials/rules/

**Comment by chakir123123** [comment]
Hi, I reduced the blacklist threshold to 3 and tested it with the payload you mentioned, but it doesn't work.
Thank you for your  reply.

**Comment by zit-hb** [comment]
I missed the reply, now it is probably too late. I suspect the connector was not correctly loaded. It can be easily verified with `phpinfo()`. Closing the issue but feel free to reopen it.
