### ISSUE TITLE
Where can I find debug log?

### ISSUE THREAD

**Issue by viktorix** [zecure/shadowd_php#29]
Hey,

I'm having a problem connecting PHP connector to Shadowd. Everything seems to be set up correctly (checked multiple times), yet there are no requests in Shadowd. I saw in troubleshooting steps there are error messages. I enabled debug in the ini file, but I can't figure out where it logs errors. Where can I find them? PHP error log doesn't have anything.

Thanks.

**Comment by zit-hb** [comment]
Hey. Error messages are passed to `error_log()`, so you should see them indeed in the error.log file. If there is nothing try to create a `phpinfo();` file to see if the connector is really properly loaded.

**Comment by viktorix** [comment]
Thanks. Yes, in all my tests connector file is included. I was able to confirm connector is working and reading ini file. I commented key line, and was able to see error for missing key. So connector is working, but requests aren't making to shadowd for some reason. Once ini file has all the proper settings, no errors are generated but requests are still missing from shadowd.

Shadowd is in the Docker, while the connector is being tested with WordPress using Nginx/PHP-FPM (7.3) on the same server.

Profile has * for the IP and is in passive mode. The connector is set to observe mode, too. I checked port 9115, it's open.

```
docker-pr 19562     root    4u  IPv6 21318576      0t0  TCP *:8080 (LISTEN)
docker-pr 19595     root    4u  IPv6 21318653      0t0  TCP *:9115 (LISTEN)
```
Followed all the installation steps, nothing should be different.

Any ideas? Thanks.

**Comment by zit-hb** [comment]
My pleasure. That behavior sounds good, I think your test attacks just do not reach the blacklist threshold, since the default blacklist threshold is quite high. It is probably at `10` at the moment. Try to set it to `2` in the profile, this way everything that slightly looks like an attack should be detected.

**Comment by viktorix** [comment]
Thanks. The problem was me. I misunderstood how Shadowd works with requests
and filters. Now I better understand it and was able to test requests.

Quick question, is connector compatible with PHP 8?

Thanks a lot.

**Comment by zit-hb** [comment]
Sorry, I missed the last response. It is fully compatible with PHP 8.

Not that it is relevant anymore but I released a new version of the connector: now error messages can be displayed directly in the error page of the connector, so debugging problems should be much easier.
