### ISSUE TITLE
error php-connector

### ISSUE THREAD

**Issue by Thuong1234** [zecure/shadowd_php#35]
i try to install shadowd and php connect on centos use nginx as reverse proxy. when i set up php connect i got some error, i can't fix. please help me.
![Screenshot (615)](https://user-images.githubusercontent.com/41165321/117991531-56d98a00-b368-11eb-9dd3-14efe8bbcae4.png)

**Comment by zit-hb** [comment]
Did you install the shadowd connector in the reverse proxy? That will not work, the connector intercepts on application level. A reverse proxy is not on application level.

The connector has to be installed for the PHP interpreter that actually executes the application. Of course it is no problem to then forward requests to that server with a reverse proxy.
