### ISSUE TITLE
some php fatal error when running some application

### ISSUE THREAD

**Issue by elico** [zecure/shadowd_php#4]
I have installed and configured shadowd and the shadowd_php connector in the php.ini.
Now when I run a simple phpinfo() it's running fine also when I ran some echo "X"; everything works fine.
But when I am trying to run applications like phpsysinfo I am starting to get some errors.
I made sure that phpsysinfo works without  the auto_prepend and after I add it and restart the service I see errors like:
PHP Fatal error:  Class 'Template' not found in /var/www/html/sysinfo/index.php on line 71

I have enabled debug but it seems like something is either no being loaded or something is being loaded wrongly in the connector.

**Comment by zit-hb** [comment]
Thanks for the report. PhpSysInfo is using the old (not recommended) `__autoload` method to load classes. It was not called anymore, because shadowd_php uses (the recommended) `spl_autoload_register`. I have released a new version (2.0.1) that fixes this problem.

Best regards,
Hendrik

**Comment by elico** [comment]
Thank you very very much!
