### ISSUE TITLE
Default timeout is 0, not 5 as intended

### ISSUE THREAD

**Issue by sloonz** [zecure/shadowd_php#42]
If shadowd in installed on a different host than the connector, the connection times out unless `timeout = 5` is set in the connection configuration file.

After a bit of debugging, `$config->get('timeout')` (in Connector.php) always returns false, which means that `(int)$this->options['timeout']` (in Connection.php) is 0 for the default configuration.

**Comment by zit-hb** [comment]
Thanks for the report, @sloonz ! It is fixed in shadowd_php 2.1.1.
