### ISSUE TITLE
shadowd_php is supported php5.6

### ISSUE THREAD

**Issue by rrpnarola** [zecure/shadowd_php#43]
I am trying to configure the shadowd_php connector but it's give me an error to mbstring so maybe it's not supporting.

Would you please suggest how we can use PHP 5.6?
![image](https://user-images.githubusercontent.com/59678895/136010203-7ec7e76d-7bad-4b03-818e-e74374036203.png)

**Comment by zit-hb** [comment]
In general I would highly recommend to move away from PHP 5.6. If you are stuck with it you can use shadowd_php 2.0.2, PHP 5 support was dropped in 2.1.0.
