### ISSUE TITLE
DVWA loads a blank site after adding the PHP connector

### ISSUE THREAD

**Issue by dattmckdj** [zecure/shadowd_php#49]
Hi,

On an Ubuntu 20.04 virtual machine which is installed both DVWA and the Shadow Daemon, after I add the directory of the shadowd.php file (_/usr/share/shadowd/php/shadowd.php_) to the auto_prepend_file parameter in the php.ini file (_/etc/php/7.4/apache2/php.ini_), the DVWA site cannot be loaded, displayed as a blank site. But when I comment out the auto_prepend_file parameter and restart the apache2 service, the site is loaded normally.

Hope you can help me with this.
If you need anything else, please let me know.

Best regards,
DatTM

**Comment by zit-hb** [comment]
Hi DatTM,

Please have a look at the error log of your server (most likely `/var/log/apache2/error.log`). I assume it contains a hint why the script can not be loaded.

**Comment by dattmckdj** [comment]
Hi zit-hb,

I found this line in the error log of the server:
_PHP Fatal error:  require(): Failed opening required '/usr/share/shadowd/php/vendor/composer/../../inc/Constants.php' (include_path='.:/usr/share/php') in /usr/share/shadowd/php/vendor/composer/autoload_real.php on line 71_
It seems the file **Constants.php** is not found in the _vendor_ folder of the PHP connector.
I re-downloaded but the mentioned file is not found in the compressed file either.

**Comment by zit-hb** [comment]
It should not be in the vendor folder but this directory (according to your logs): `/usr/share/shadowd/php/inc/Constants.php`. Can you confirm manually that it exists? If it exists it might be a permission problem. Make sure that the directories and files are readable by your web server user (e.g. `www-data`).

> I re-downloaded but the mentioned file is not found in the compressed file either.

What file did you download? When I download the latest release here at Github the file exists.

**Comment by dattmckdj** [comment]
> 

Hi @zit-hb,

I have found the file in the _inc_ folder and am able to reload the site successfully.
However, when I change the state of the profile to active, all traffic to the web app seems to be blocked (as in the screenshot below).
Is this behavior expected if the ignored rules are not imported?
![image](https://user-images.githubusercontent.com/66473757/148769188-87682016-a3f9-43f7-a89c-317749b4d177.png)

**Comment by zit-hb** [comment]
Hello @dattmse140171,

It has nothing to do with ignored entries. The most likely explanation is that you have activated the integrity check but have not specified integrity rules (or incorrect ones). As explained [here](https://shadowd.zecure.org/documentation/integrity/), the integrity check requires a valid rule for every file, otherwise the request will be blocked. This makes sense since the integrity check is supposed to block modified or new files (e.g., a backdoor that was uploaded).

If you look at the request/parameters page you will also see why the request is blocked. If you see the `Unknown` tag next to the caller that means there is no integrity rule for this caller.

**Comment by dattmckdj** [comment]
Hi @zit-hb,

Sorry for the delayed response.
I can resolve the issue after disabling the integrity of the profile.

**Comment by mpermana7** [comment]
> > 
> 
> Hi @zit-hb,
> 
> I have found the file in the _inc_ folder and am able to reload the site successfully. However, when I change the state of the profile to active, all traffic to the web app seems to be blocked (as in the screenshot below). Is this behavior expected if the ignored rules are not imported? ![image](https://user-images.githubusercontent.com/66473757/148769188-87682016-a3f9-43f7-a89c-317749b4d177.png)

can anyone help me make a tutorial on how to connect shadow daemon to dvwa?

**Comment by dattmckdj** [comment]
Hi @mpermana7,
zit-hb has a documentation site that contains the instruction on how to connect the WAF to the web app.

**Comment by mpermana7** [comment]
> Hi @mpermana7, zit-hb has a documentation site that contains the instruction on how to connect the WAF to the web app.

please, help me for how to connect the shadow daemon to DVWA, pleaseeeee, i want detail tutorial, from installation until finish
this my email : mochamadpermana@gmail.com and my instagram : mpermana7
