### ISSUE TITLE
can anyone help me make a tutorial on how to connect shadow daemon to dvwa?

### ISSUE THREAD

**Issue by mpermana7** [zecure/shadowd_php#51]

**Comment by mpermana7** [comment]
I have successfully installed the shadow daemon, but I don't know how to connect the shadow daemon with DVWA
![image](https://user-images.githubusercontent.com/59886301/158437603-8b69aefc-40b5-4654-8354-6849a39625d7.png)

**Comment by zit-hb** [comment]
Hello,

the documentation is basically a tutorial.

1. You create a profile: https://shadowd.zecure.org/overview/user_interface/
2. You install the PHP connector on the web server that hosts the DVWA: https://shadowd.zecure.org/overview/php_connector/

**Comment by mpermana7** [comment]
> Hello,
> 
> 
> 
> the documentation is basically a tutorial.
> 
> 
> 
> 1. You create a profile: https://shadowd.zecure.org/overview/user_interface/
> 
> 2. You install the PHP connector on the web server that hosts the DVWA: https://shadowd.zecure.org/overview/php_connector/

I've done that, after that what should I do?  what files should I configure?  I need a detailed tutorial, thank you

**Comment by mpermana7** [comment]
![image](https://user-images.githubusercontent.com/59886301/158853563-8e2ebe1c-b907-472d-86b5-2ce3fc84dad7.jpeg)

Is the configuration in the php.ini file correct?  if wrong please show me the correct configuration

**Comment by zit-hb** [comment]
Yes, it is correct.
