### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by akm4747** [zecure/shadowd_php#6]
Hello there,

I am trying to setup shadowd on my test box and having an issue. Can anyone please help?

Once I configured (trying to configure) the php connector I am not able to load my wordpress test site. I enabled the shadow globally (php.ini) and I am using nginx/1.2.1. 

I am getting the following error message when executing "php index.php".
Undefined index: SERVER_PROTOCOL in /usr/share/shadowd/php/Output.php on line 28

**Comment by zit-hb** [comment]
Hey,

you are seeing the SERVER_PROTOCOL error, because you called the file via the command line and the variable is set by your web server. Shadow Daemon only works in combination with a web server.

If your blog is not loading and you have enabled "passive mode" for the profile this means that the connector is not able to connect to the shadowd server. Make sure that you have set "profile" and "key" correctly in your config file /etc/shadowd/connectors.ini (https://github.com/zecure/shadowd_php/blob/master/misc/examples/connectors.ini#L2-L6) and that the file is readable by your web server user. You should also enable "debug" in the config, this way you can see in your web server error log what is causing the problem (/var/log/nginx/error.log).

Best regards,
Hendrik

**Comment by akm4747** [comment]
Thanks Hendrik for the quick reply.

The test blog can be loaded once I enable the observe. I also enabled the debug and getting a bad request: [error] 12195#0: *1450 FastCGI sent in stderr: "PHP message: shadowd: bad request" while reading response header from upstream, client:

Once the observe is disabled the test blog won't load. The key id and profile id are set as I was playing with the ids and once they are wrong an error will be within ...nginx/error.log that   

I am still not able to figure out why I am getting the bad request once the observe is disabled. 

Any help will be much appreciated.

**Comment by zit-hb** [comment]
When "observe" is enabled there will never be an error. I added this setting in case you want to log attacks but don't want to disclose the presence of Shadow Daemon in case of a problem (aka [honeypot](https://shadowd.zecure.org/tutorials/honeypots/)).

There are multiple reasons why a "bad request" can happen, but the most likely one is that no profile with the id and server ip is found. May I ask what you have set as profile id and server ip? For comparison (https://demo.shadowd.zecure.org/profiles), here the profile ids are 1 and 2 and the server ips are 127.0.0.1. I recommend to set asterisk (*) as server ip, so connections from every ip are allowed.

**Comment by akm4747** [comment]
Thank you so much for pointing me to the right direction. 
I set the profile id as 1 and the server ip as 127.0.0.1, also, I am using the asterisk (*) as server ip in the profile. The issue was that I wrongly assigned my server ip. 

Thank you again. 

One more question, once I enable the "Integrity", I am getting "500 Internal Server Error" while trying to load the test blog from my browser. The error message on nginx/error.log is [error] 12197#0: *2334 FastCGI sent in stderr: "PHP message: shadowd: stopped critical attack from client: my box ip” while reading response header from upstream, client: my box ip, server: wordpress.link, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: “wordpress.link”, referrer: "http://wordpress.link/“

Once the "Integrity" is disabled, I am able to load my test blog without a problem.

**Comment by zit-hb** [comment]
I am glad that it worked out. You are welcome.

The integrity check needs a rule for every file that should be callable. I explain it in more detail here: https://shadowd.zecure.org/documentation/integrity/

So if you want to use the integrity check you will have to create rules for it. You can use the generator for this: https://shadowd.zecure.org/tutorials/rules/

**Comment by akm4747** [comment]
I was able to set integrity rules and all works

Thank you again.
