### ISSUE TITLE
A required to initialize Shadow Daemon waf is corrupted and can not be parsed.

### ISSUE THREAD

**Issue by alvirahesc** [zecure/shadowd_php#60]
Hi, Ive been trying to use Shadow Daemon with LAMPP and I have followed the installation steps provided in the official site. But it does not seem to work, and there is no request appear in the Shadow Daemon GUI. Also nothing appeared in /var/log/shadowd.log which I made using mkdir and nano.

Here's my profile settings which I changed in the GUI:
ID:1
Flooding Treshold 3

And here's my connectors.ini content:
profile:1
debug:1
Observe:1

When I access 127.0.0.1 I get a page with this message:

Warning: parse_ini_file (etc/shadowd/connectors.ini): failed to open stream:
Permission denied in /usr/share/shadowd/php/src/Config.php on line 49  

Where could I have been mistaken?
![image](https://user-images.githubusercontent.com/61485986/183289403-cf4ecbba-467d-4f70-8e04-633656acd7b3.png)

**Comment by alvirahesc** [comment]
So apparently by giving chmod 777 to connectors.ini fixed this issue.

But there is still no requests appearing in GUI even if I try to do SQL injection. I am so confused as to where I went wrong.
Im using LAMPP, I put my webapp under /opt/lampp/htdocs.

Please help me, Sir @zit-hb I need this for a college project.

**Comment by zit-hb** [comment]
Hello @alvirahesc, it is explained on this page how to load the connector and what permissions are required: https://shadowd.zecure.org/overview/php_connector/

If you think you have done that correctly, create a file with this content and check the `auto_prepend_file` value there: `<?php phpinfo();`. If the connector does not show up there, try restarting Apache. If it does show up, try reducing the blacklist threshold of the profile to `1`.

**Comment by alvirahesc** [comment]
I am very glad for your quick respond, @zit-hb. I hope you would not mind using your time to help me as this is important to me.

So, I did what you said, here's the result from phpinfo
![image](https://user-images.githubusercontent.com/61485986/183313973-7d0a7933-7a4a-4731-b826-877b2ad210fc.png)

And there is still no request appearing no matter what I did on the web app.
![image](https://user-images.githubusercontent.com/61485986/183314064-c8764b14-45db-4023-8114-43db7bef849a.png)

Here I will give you the detail of my configurations.
This is where I put Shadow Daemon files, connectors, and my web app "lintasarta" and "test" website.
![image](https://user-images.githubusercontent.com/61485986/183314352-2877a371-93ef-445a-aa7a-2763e01bb5ea.png)

My connectors.ini file:
![image](https://user-images.githubusercontent.com/61485986/183314317-5dcf41a7-fc48-42e9-afe3-bd2ede77877f.png)

This is my docker containers status
![image](https://user-images.githubusercontent.com/61485986/183313917-10c706a7-25bf-4ed2-904b-51625c7e7b35.png)

I just gave chmod 777 to the connectors.ini file just to see if Shadow Daemon is working properly, but apparently it is not at the moment.

**Comment by alvirahesc** [comment]
I know it's showed that connector is apparently loaded in the phpinfo but I will just show you where I put the connector directory. 

/opt/lampp/etc/php.ini
![image](https://user-images.githubusercontent.com/61485986/183314574-105c7d28-5e64-4810-96e2-b8c4e76aae93.png)

And I expect error messages to appear /var/log/shadowd.log which I created, but its always empty. 
![image](https://user-images.githubusercontent.com/61485986/183314705-275686a8-e68a-428d-8c64-e5e9be430d20.png)

**Comment by alvirahesc** [comment]
I used pentest apps to attack the webapp and it works!!!
